web:
  build: .
  volumes:
   - .:/go/src/github.com/alveary/overseer
  environment:
    OVERSEER_REDIS_HOST: redis
    OVERSEER_REDIS_PORT: 6379
  links:
   - redis
redis:
  image: redis
proxy:
  # image: mechanoid/haproxy-scale
  build: /Users/falkh/code/gihub.com/alveary/haproxy-scale
  restart: always
  environment:
    PROXY_APP_PORT: 8080
    PROXY_APP_PREFIX: web
  ports:
    - "8000:80"
  links:
    - web
